require "capybara"
require "form_object_model/version"
require "form_object_model/form.rb"
require "form_object_model/helper.rb"
require "form_object_model/matcher.rb"
require "form_object_model/field.rb"
require "form_object_model/text_field.rb"
require "form_object_model/select_field.rb"
require "form_object_model/radio_field.rb"

